services:
  - type: web
    name: gtm-audit-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: GEMINI_API_KEY
        value: your-gemini-api-key
    region: oregon
    plan: free